SibylLab/Program-Wars

src/components/SettingsComponent.vue

Added a remove button next to the player names in the game setting phase.

Can now remove players from the list in the game setting phase

---

src/components/SettingsComponent.vue

Changed the score to win selection box to have three options, 10, 20, or 30 points. 
fix #43

Changed the score to win to three options

---

.codeclimate.yml
.travis.yml
npm-shrinkwrap.json

Looks like the issue was the path to the LCOV file.

Getting code coverage to work

---

src/components/MainComponent.vue
src/components/OpponentStack.vue
src/components/Stack.vue

Looked at each TODO, all have been already implemented or was not relevant. They have been removed from the code as well as some unneeded commented out code. 
fix #25 
fix #27 
fix #28 
fix #29 
fix #30 
fix #31 
fix #32 
fix #33 
fix #34 
fix #35 
fix #26 (HACK is actually the title of the button when hacking, not an issue)

Removed unused TODO's

---

src/classes/Deck.js
src/store/mutations.js
test/unit/specs/Deck.spec.js

The deck is now dynamic and will grow as more players are added, it is currently at 50 cards/player.
fix #48

Card distribution

---

src/classes/Deck.js
src/components/Card.vue
src/components/MainComponent.vue
src/components/Modal.vue
src/components/OpponentStack.vue
src/components/OpponentStacks.vue
src/components/PlayerInfoPanel.vue
src/components/Playfield.vue
src/components/SettingsComponent.vue
src/components/Stack.vue
src/store/mutations.js
src/store/store.js

Removed all unneeded `console.log()`, I also changed some of the spacing and deleted unused empty functions.

Cleaned up some of the code

---

src/components/MainComponent.vue

Fixing issue that caused the score limit to not update after a new game was started. 
fix #47

Score Updating Fix

---

src/components/CreditsModal.vue
src/components/MainComponent.vue
src/components/SettingsComponent.vue

Changed how the credits modal is generated, changed the text, removed the gif, and added background colours to the game setting modal, rules modal, and credits modal. 
@johnanvik please advise what to add/change in the credits text.
fix #79

Credits Modal

---

src/components/OpponentStack.vue
src/components/SettingsComponent.vue

Redesigned the settings page, added rules and credits to the header. 
Removing players after the "Maximum player count" message appears will make the message go away. 
fix #102

Start page

---

src/components/PlayerInfoPanel.vue

Added a condition before ending the turn to make sure the player truly has taken his/her turn. I also added a 1 second delay from the time the player plays a card and the modal showing the next player shows up.
fix #114

End turn fix

---

src/components/PlayerInfoPanel.vue

Added a line above the score showing what the target score is. 
fix #131

Target Score

---

src/components/SettingsComponent.vue
src/store/mutations.js

The player list is no longer reseted between games unless the page is refreshed. 
fix #44

Remembering Players

---

test/unit/karma.conf.js
test/unit/specs/Deck.spec.js

fixed the code climate error. 
fix #93

Addressed Code Climate Issues

---

src/classes/Deck.js
src/components/PlayerInfoPanel.vue
src/components/SettingsComponent.vue
src/store/mutations.js
test/unit/specs/Deck.spec.js

If the deck is empty it will shuffle the discard pile and use those as the new deck. Did minor testing to make sure it works. Unit testing to be added to assure it is working properly for different cases, will address when on #94.
fix #73

Shuffle discard cards

---

README.md
docs/CONTRIBUTING.md

A document pointing people to how they can help with the project.

Contributions document

---

docs/ISSUE_TEMPLATE.md

This is a proposed template to help users in providing enough information for either a bug report or feature request.
Partially fixes #140
Provides a starting point for dealing with #107

Create issue template

---

docs/PULL_REQUEST_TEMPLATE.md

Fixes #140 
Overview
- A template  for pull requests.
Reviewer: @vincentcote87

Create pull request template

---

src/components/CreditsModal.vue

Fixes #123 
-Katherine Hatton has been added to the credits.
@johnanvik I have added her title as "Graphics by" please advise if you would like a different title.

Added Katherine in the credits

---

.travis.yml

- Upgrading to new CodeClimate test reporter

Updating to use new CodeClimate test reporter

---

.travis.yml

Addresses \#167
- Removed deplyment to production commands as they are now causing the CI server to hang after the build is complete.
Reviewer: @vincentcote87

CI Hung up

---

src/components/MainComponent.vue
src/store/store.js

Fixes N/A
- Accidentally removed some key code when merging in from GitHub.

Merge into master ASAP

---

src/components/MainComponent.vue
src/components/WinnerModal.vue

Fixes #169 
- Changed the routing to use a function to push to the settings page instead of using the <router-link> tag provided. New game and close button in the winner modal now work in Firefox

Changed routing to work in Firefox

---

src/components/SettingsComponent.vue

Fixes #188 
- Short game score was 10, now 15
- Medium game score was 20, now 25
- Long game score was 35, now 35

Changed winning score totals

---

src/classes/Deck.js
test/unit/specs/Deck.spec.js

Fixes #187 
- Added Variable 5 and 6. 
- Removed Variable 2.
- Changed the amount of V4 cards and Rx cards.

Added V5 and V6, removed V2

---

src/components/MainComponent.vue
src/store/actions.js

Fixes #196
- The game will no longer get hung up if the first player is an AI.

Added function for ai to take turn if first

---

src/classes/Personality.js
src/classes/Player.js
src/classes/Sprinter.js
src/components/MainComponent.vue
src/store/actions.js

Fixes #194
- Picking an AI will generate random personality.

Random personalities

---

src/classes/AiMove.js
src/classes/Gambler.js
src/classes/Hacker.js
src/classes/Personality.js
src/classes/Sprinter.js
src/components/SettingsComponent.vue
src/store/getters.js
src/store/mutations.js

Fixes N/A (partial fix for #189)
- AI opponents can now use variable cards.
- Added a new personality, the gambler. It will always use Rx cards first in order to use Variables.
- Other personalities can also use Rx and variables, will only do it if has no other move and has both an Rx and a Variable in current hand.
- Refactored how each personality calls the common functions, uses a common AiMove.js file for code that was repeat.

Ai variables

---

index.html
src/components/SettingsComponent.vue

Fixes #215
-Changed the link to bootswatch to load properly

Bootstrap theme fix

---

development/cardGraphicsOriginal/Group_Cards.ai
development/cardGraphicsOriginal/Hack_Card.ai
development/cardGraphicsOriginal/Instruction_Cards.ai
development/cardGraphicsOriginal/Repetition_Cards.ai
development/cardGraphicsOriginal/Variable_Cards.ai
src/components/Card.vue
src/components/SettingsComponent.vue

Fixes N/A
- Added the original card graphics illustrator files from Katherine to keep with the project

Adding files

---

.travis.yml
src/components/SettingsComponent.vue

New master

---

.travis.yml

Fixes \#\<Issue number\>
-
-
-

Live branch

---

src/components/TutorialStartModal.vue

- Changed text to (hopefully) be clearer.
Reviewer: @JaceRiehl

Updating Tutorial text

---

src/classes/Deck.js
src/classes/Player.js
src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/CardModals/OverclockModal.vue
src/components/SharedComponents/Card.vue
src/components/SharedComponents/DisplayUsedCards.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue
src/store/mutations.js

Fixes #300 
Fixes #299 
- Changed the info panel to displaying benefit cards and cards you've been attacked by.
- Added a display meter instead of displaying the score.

Changed the info panel to displaying cards used

---

src/classes/Deck.js
src/classes/Player.js
src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/RulesModal.vue
src/components/Modals/WinnerModal.vue
src/components/SharedComponents/Playfield.vue
src/components/SharedComponents/SettingsComponent.vue
src/components/SharedComponents/Stack.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue
src/store/getters.js
src/store/mutations.js
test/unit/specs/Deck.spec.js

Fixes #70 ?
Fixes #302 
Fixes #303 
Fixes #309 
Fixes #310 
Fixes #311
Fixes #313 
Fixes #315 
Fixes #317 
- Reworks the scoring system and scoring balance with card bonuses and number of cards in the deck.
- Changes the winning modal with scoring breakdowns. 
- Fixes a bug with the Rx card. 
- Fixes the bug not allowing users to continue playing the tutorial after it's been finished. 
- Fixed a bug that would display the wrong tutorial step in the text box. 
- Added a section in the rules to tell people how to get bonus points and good programming practices to use.

Scoring Rework

---

src/classes/Deck.js
src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/RulesModal.vue
src/store/mutations.js
test/unit/specs/Deck.spec.js

Fixes #320
Fixes #321 
Fixes #324 
Fixes #325 
- Fixes the scoring calculation
- Fixes the safety cards not removing their attack counters bug
- Adds only one of each safety card to the entire deck
- Adds a section about refactoring.

Scoring and Rules fixes

---

package-lock.json
src/components/MainGame/MainComponent.vue
src/components/Modals/CardModals/AntiVirusModal.vue
src/components/Modals/CardModals/BatteryBackup.vue
src/components/Modals/CardModals/Firewall.vue
src/components/Modals/CardModals/Generator.vue
src/components/Modals/CardModals/HackModal.vue
src/components/Modals/CardModals/OverclockModal.vue
src/components/Modals/CardModals/PowerOutageModal.vue
src/components/Modals/CardModals/VirusModal.vue
src/components/SharedComponents/Stack.vue
src/components/Tutorial/TutorialComponent.vue
src/store/mutations.js

Fixes #349
- Fixes the issues from Deep Scan.

Fixed the errors from Deepscan

---

src/components/Modals/CreditsModal.vue

Fixes #104 
- Adds a dynamic version number tag to the credits modal.

Dynamic vn

---

.travis.yml

Fixes #328 
- Changed .travis.yml to deploy application to Firebase
Reviewer: @JaceRiehl

Firebase deployment

---

src/components/SharedComponents/Card.vue

Fixes #354 
- Fixed the bug with the Ai showing their hand.

Fixed the Ai Hand bug

---

static/UserStudy/StudyCodeExamples.pas

- Adds pascal code examples for the user study that reflect all of the different types of coding cards in the game. There are some hard examples where we might break it down into smaller pieces for them to analyze and easy examples that cover one specific topic. There are two versions of each easy example, one for each of the pre and post study. I've left the math in each code example (and their alternatives) easy and similar so that it's not about the math but rather if they understand the coding fundamental. Could I get some feedback on this? I'm stuck as to where to go from here on the code examples. 

Pascal examples

---

src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/CardModals/AntiVirusModal.vue
src/components/Modals/CardModals/BatteryBackup.vue
src/components/Modals/CardModals/Firewall.vue
src/components/Modals/CardModals/Generator.vue
src/components/Modals/CardModals/HackModal.vue
src/components/Modals/CardModals/OverclockModal.vue
src/components/Modals/CardModals/PowerOutageModal.vue
src/components/Modals/CardModals/VirusModal.vue
src/components/SharedComponents/SettingsComponent.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue

Fixes #264 
Fixes #369 
- Added changes that fixed the cross compatibility issues between browsers. The ones I've tested are Safari, Chrome, and Firefox. I can't test Microsoft Edge because I have a Mac. 
- Fixed many issues related to the resolution of the game on players screens. I've tested them from a 32" monitor to 13" laptop screen (and smaller than the 13" fullscreen) and it looks good on all of them now. The one thing that I can't fix it how the bootstrap panels (the tip box) work when they're squished too much with too much text. It will elongate the tip box and not look great. 

Browser cross compatibility and Resolution

---

src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/CardModals/AntiVirusModal.vue
src/components/Modals/CardModals/BatteryBackup.vue
src/components/Modals/CardModals/Firewall.vue
src/components/Modals/CardModals/Generator.vue
src/components/Modals/CardModals/OverclockModal.vue
src/components/Modals/CardModals/PowerOutageModal.vue
src/components/Modals/CardModals/VirusModal.vue
src/components/SharedComponents/OpponentStack.vue
src/components/SharedComponents/SettingsComponent.vue
src/components/SharedComponents/Stack.vue
src/components/Tutorial/TutorialComponent.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue
src/store/mutations.js
src/store/store.js

Fixes #370
- Fixes a bug with the tip box not resetting when a card is played. This allowed the player after you to see what you played. 
- Fixed a bug in the tutorial text box that didn't correctly say what card to play.

Tip box bug

---

src/classes/AiActions/AiMove.js
src/components/MainGame/MainComponent.vue
src/components/Tutorial/TutorialComponent.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue
src/store/actions.js
src/store/mutations.js

Fixes #374 
Fixes #376 
- Fixes the games state. This prevents code from continuing to run after the route has been changed to the main page. This fixes it so that the MainComponent.vue and TutorialComponent.vue can't interact with the state set by the other. 
- Fixes the AiMove bugs from the Mocking merge. 

Tutorial state fix

---

package-lock.json
package.json
src/components/MainGame/MainComponent.vue
src/components/SharedComponents/Timer.vue
src/components/Tutorial/TutorialComponent.vue
src/store/actions.js
src/store/getters.js
src/store/mutations.js
src/store/store.js

Fixes #383
- Added a game timer. 

Game timer

---

src/classes/Models/Card.js
src/components/MainGame/MainComponent.vue
src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/RulesModal.vue
src/components/SharedComponents/Card.vue
src/components/SharedComponents/DisplayUsedCards.vue
src/components/SharedComponents/Stack.vue
src/components/SharedComponents/Timer.vue
src/components/Tutorial/TutorialComponent.vue
src/store/store.js

Fixes #378
Fixes #398 
- Fixes the UI to make the game less vertical. 
I'm not sure if this is ready to be merged. When more than two players are added it increased the vertical length of the game. Which is the problem we were trying to avoid. Will talk about this in the meeting.

Ui redesign

---

src/components/MainGame/MainComponent.vue
src/components/Modals/CoinModal.vue
src/store/actions.js

Fixes #403 
- Changed the modal and the times that it is displayed. 
- Let me know what you think about the times. I'm trying to find a balance between the modals being displayed too long and being able to read what they say. I think the user would rather the modals be finished quicker after they've read it the first time.

Changed Coin Modal

---

src/components/SharedComponents/Stack.vue

Fixes #404 
- Doesn't allow the user to play repeats, variables, or group cards while they're under a power outage.

Fixed power outage behaviour

---

src/components/SharedComponents/Stack.vue

Fixes #423 
- Fixes the behaviour of the the group card.

Card behaviour

---

src/classes/Models/Player.js
src/components/MainGame/PlayerInfoPanel.vue

Fixes #424
- Fixed the redraw option so that users can no longer redraw multiple times.

Fixed the redraw option from allowing the user to redraw multiple times.

---

src/components/SharedComponents/DisplayUsedCards.vue

Fixes #428 
- Changed the terms for the displayUsedCards panel to make sense with the game. 

Changed the used cards panel names to make more sense with the game.

---

src/classes/AiActions/BatteryBackupStep.js
src/classes/Models/Deck.js
src/components/Modals/CardModals/BatteryBackup.vue
src/store/mutations.js

Fixes #437
- Removes battery cards when a generator is played.

Removes battery backups when a generator is played

---

src/components/SharedComponents/DisplayUsedCards.vue

Changed labels to a more "cybersecurity" theme

---

src/components/MainGame/MainComponent.vue
src/components/MainGame/PlayerInfoPanel.vue
src/components/Modals/CardModals/PowerOutageModal.vue
src/components/Modals/RulesModal.vue
src/components/SharedComponents/SettingsComponent.vue
src/components/Tutorial/TutorialComponent.vue
src/components/Tutorial/TutorialPlayerInfoPanel.vue

- Fixed the OverClock file error typo in the rules modal. Hopefully this fixes the rules modal bug.

Changed the OverClock file path error in the rules modal.

---

src/components/Modals/CreditsModal.vue

- Added John Jr. to the credits. 

Added John Jr to the credits.

---

src/classes/Models/Player.js
src/components/MainGame/MainComponent.vue
src/components/Modals/WinnerModal.vue
src/components/SharedComponents/Conditionals.vue
src/components/SharedComponents/Playfield.vue
src/components/SharedComponents/SettingsComponent.vue
src/components/SharedComponents/Stack.vue
src/store/actions.js
src/store/getters.js
src/store/mutations.js
src/store/store.js

Fixes #489
-1 playfield instead of 1
-removed true/false and player name pop-up
-added side objectives that update the player on the progress of their end game bonus'

Conditionals rework

---

src/components/SharedComponents/SettingsComponent.vue

Fixes #504 
- Commented out Tutorial link
Reviewer: @groadybones

Disable tutorial button

---

src/components/Modals/RulesModal.vue
src/components/SharedComponents/Playfield.vue

fixed bugs for cards overlapping
Fixes #506
- Added margins around the stacks

Increase spacing between cards

---

src/components/Modals/WinnerModal.vue

Updated WinnerModal.vue
Fixes #533
- game ends when the score is less than target score
- 
-

Matching exact score doesn't end game

---

src/components/MainGame/PlayerInfoPanel.vue
src/components/SharedComponents/Playfield.vue
src/store/store.js

Fixes #531
Fixes #532
-players scores moved to the top left, above progress bar
-score limit moved towards left above progress bar
-

grouped current scores and target scores

---

.travis.yml

last small adjustment as suggested in some of the documentation that may fix the deployment issue.

One last thing to try to fix authentication problem for firebase deploy.

---

.travis.yml
README.md
jest.config.js
package-lock.json
package.json
src/classes/game/CyberEffect.js
src/classes/game/Deck.js
src/classes/game/GroupedStacks.js
src/classes/game/Objectives.js
src/classes/game/Player.js
src/classes/game/Stack.js
src/classes/game/Trojan.js
src/components/game/EffectNotifications.vue
src/components/game/PlayerInfo.vue
src/components/game/SideObjectives.vue
src/components/game/TurnHistory.vue
src/components/modals/WinnerModal.vue
src/store/actions.js
src/store/mutations.js
src/store/store.js
tests/unit/Objectives.spec.js
tests/unit/actions.spec.js
tests/unit/mutations.spec.js

Fixes nothing specific
- Added documentation to a few files that needed it.
- Tweaked documentation for some other files.
- Broke up an action to make it simpler and fixed tests.
- Changed some variable use in a mutation to make it more coherent.
- Set up spy hand window so that it will always be centered.

V2small fixes

---

src/components/shared/SideMenu.vue

Fixed URL link
Fixes #612 
-Fixed URL for Report Issue
-
-

Report-issue

---

src/components/game/EffectNotifications.vue
src/components/game/TurnHistory.vue

Fixes None
- Removed some redundant conditions
- Removed default initialisation of a variable that is always overwritten
- These changes were recommended code quality fixes from deepScan

Made changes recomended by deepscan.

---

README.md

Fixes #622
- Updated DeepScan project to reflect new GitHub location
- Updated URL for badge
Reviewer: @strinsberg

Update DeepScan badge

---

src/components/modals/WinnerModal.vue
src/components/modals/WinnerModalBeginner.vue

Post game URL added
